spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://localhost:5432/mobflow_auth
spring.datasource.username=postgres
spring.datasource.password=roblox
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

security.jwt.secret-key=bXktc3VwZXItc2VjcmV0LWtleS0xMjM0NTY3ODkwMTIzNDU2Nzg5MA==
security.jwt.expiration-time=900000

server.port=8087

